# Generated by Django 3.2.7 on 2021-09-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
