# Generated by Django 3.2.7 on 2021-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210913_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.AddField(
            model_name='container',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='container',
            name='port',
            field=models.IntegerField(default=5000),
        ),
    ]
